name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK with Buildozer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip build-essential \
              libssl-dev libffi-dev libncurses6 libncurses6-dev libsqlite3-dev \
              zlib1g-dev libgdbm-dev libc6-dev libbz2-dev libreadline-dev \
              libsqlite3-dev wget liblzma-dev libegl1

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Create buildozer.spec if not exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
