name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: $HOME/android-sdk
      PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Gerekli Araçları Kur
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk tar wget
        pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Android SDK Kurulumu
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mkdir -p latest && mv cmdline-tools/* latest/

        yes | sdkmanager --licenses || true
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Buildozer Ayar Dosyasını Hazırla
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        sed -i 's/^package.name = .*/package.name = myapp/' buildozer.spec
        sed -i 's/^package.domain = .*/package.domain = org.test/' buildozer.spec
        sed -i '/^#*android.accept_sdk_license/s/^#*/ /;s/=.*/= True/' buildozer.spec

    - name: APK Oluştur
      run: buildozer android debug

    - name: APK'yi Yükle
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk
