name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: stable

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp-apk
          path: bin/*.apk   # APK dosyasının bulunduğu klasör ve yol
