name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Gereklilikleri Kur
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk libncurses6 libstdc++6
        pip install --upgrade pip
        pip install cython==0.29.36
        pip install buildozer
        mkdir -p $HOME/cmdline-tools
        cd $HOME/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        mv cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
        yes | sdkmanager --licenses || true

    - name: Ensure buildozer.spec exists
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        sed -i 's/^package.name = .*/package.name = myapp/' buildozer.spec
        sed -i 's/^package.domain = .*/package.domain = org.test/' buildozer.spec

    - name: APK Olustur
      run: |
        buildozer android debug

    - name: APK Yolla
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk
