name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v2

    - name: Gereksinimleri yükle
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk libncurses5 libstdc++6
        pip install --upgrade pip
        pip install cython==0.29.36
        pip install buildozer
        pip install "kivy[base]"==2.2.1

    - name: APK oluştur
      run: |
        buildozer android debug

    - name: APK dosyasını yükle
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: bin/*.apk
