name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları çek
        uses: actions/checkout@v2

      - name: Gerekli paketleri kur
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk libncurses6 libstdc++6
          python3 -m pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer
          pip install "kivy[base]"==2.2.1

      - name: Sadece eksikse buildozer.spec oluştur
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          else
            echo "buildozer.spec zaten mevcut, geçildi."
          fi

      - name: APK oluştur
        run: buildozer android debug

      - name: APK çıktısını yedekle
        uses: actions/upload-artifact@v2
        with:
          name: my-kivy-app
          path: bin/*.apk
