name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk libncurses6 libstdc++6
        pip install --upgrade pip
        pip install cython==0.29.36
        pip install buildozer

    - name: Ensure buildozer.spec exists
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        sed -i 's/^package.name = .*/package.name = myapp/' buildozer.spec
        sed -i 's/^package.domain = .*/package.domain = org.test/' buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk
